#!/bin/sh

#Below find the commands used to map RNA-seq data. 

#Replace the variables at the top with the correct paths for the locations of files/programs on your system. 

#This bash script will map one paired end HiC dataset (read1 & read2 fastqs). Feel to modify and multiplex as you see fit to work with your volume of samples and system. 
# For the bsub lsf system

sample=$1
index=$(basename $sample |sed 's/_trim_1.fq.gz//')
prefix=$(dirname $sample)

star_index=/home/sqmao/18_Ref/correct/female/new/Mi
gtf=/home/sqmao/18_Ref/correct/female/new/Mi.gtf
 
bsub -K -J STAR1 -n 8 -o %J.STAR1.out -e %J.STAR1.err -R span[hosts=1] "module purge;module load STAR/2.6.0a-foss-2016b;STAR --runThreadN 8 --genomeDir ${star_index} \
--readFilesIn ${prefix}/${index}_trim_1.fq.gz  ${prefix}/${index}_trim_2.fq.gz \
--outSAMtype SAM --readFilesCommand zcat --alignIntronMax 50000 --outFileNamePrefix ${index}. --sjdbGTFfile $gtf  --outReadsUnmapped None"
 
bsub -K -J STAR2 -n 1 -o %J.STAR2.out -e %J.STAR2.err -R span[hosts=1] "grep -E '@|NH:i:1' ${index}.Aligned_out.sam >${index}.Aligned_out.uniqe.sam"
 
bsub -K -J STAR3 -n 2 -o %J.STAR3.out -e %J.STAR3.err -R span[hosts=1] "module purge;module load SAMtools/1.3;samtools sort -@2  ${index}.Aligned_unique.sam > ${index}.Aligned_out.bam"
 
rm ${index}.Aligned_out.sam
 
rm ${index}.Aligned_out.uniqe.sam
 
rm ${index}.Aligned_out.bam
 
bsub -K -J STAR4 -n 1 -o %J.STAR4.out -e %J.STAR4.err -R span[hosts=1] "module purge;module load HTSeq/0.8.0;htseq-count -f bam -s no ${index}.Aligned_out.bam -t gene $gtf >${index}.Genecounts 2>${index}_htseq.log"

echo "### Step 8:Thank for use this pipeline,contact us with 1140889805@qq.com"
